version: '2'

services:

  peer:
    image: rakutenrbl/multichain-peer:latest
    volumes:
      - multichain_data:/root
    ports:
      - "9578:9578"
    environment:
      CHAIN: test-chain
      PEER: rtcblockchain01.westeurope.cloudapp.azure.com:9579

volumes:
  multichain_data:
